sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - npm install
before_script:
  - npm prune
script:
  # - npm run build
  - echo "skipping build"
  # - npm test
  - echo "skipping tests"
  # create .nojekyll files
  # We are telling GitHub to not process this branch using jekyll
  - touch .nojekyll
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run lh -- --perf=80 --pwa=80 --a11y=80 --bp=80 --seo=80 https://fabriciofmsilva.com.br/notes-app/; fi'
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
