sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
  - npm prune
script:
  # - npm run build
  - echo "skipping build"
  # - npm test
  - echo "skipping tests"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
